language: python
python:
  - "2.7"
before_install:
  - pip install codecov
# command to install dependencies
install:
  - "pip install -r ./project/requirements.txt"
# command to run tests
script:
  - python -m unittest discover
  - coverage run --source=./project/tests test_parsers.py
after_success:
  - codecov
